stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./bittube/Dockerfile
      buildContext: .
      tag: easyhash/bittube:latest,build-${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
